language: python
sudo: false
services:
    - docker
branches:
    only:
        - release/personal
install:
- pip install -U tox
- pip install -r will/requirements/dev.txt
script:
- tox
- export CTAG="-$TRAVIS_COMMIT"
- "fab docker_build"
deploy:
  skip_cleanup: true
  provider: script
  script: "fab docker_deploy"
  on:
    branch: release/personal
env:
  matrix:
    secure: 
