site_name: Will's Docs
site_url: http://skoczen.github.io/will
site_description: "Will is a simple, beautiful-to-code python hipchat bot"
pages:
- ["index.md", "Get Started"]
- ["plugins/basics.md", "Teach Your Will", "The Basics"]
- ["plugins/notice.md", "Teach Your Will", "What Will Can Notice"]
- ["plugins/reply.md", "Teach Your Will", "How Will Can Respond"]
- ["plugins/acl.md", "Teach Your Will", "Access Control"]
- ["plugins/create.md", "Teach Your Will", "Creating and Organizing Plugins"]
- ["plugins/builtins.md", "Teach Your Will", "Plugin Builtins"]
- ["plugins/bundled.md", "Teach Your Will", "Bundled Plugins"]
- ["config.md", "Configure"]
- ["deploy.md", "Deploy"]
- ["improve.md", "Improve"]
theme: will
site_name: Will
theme_dir: "docs/themes/will/"
repo_url: https://github.com/skoczen/will/
copyright: Copyright &copy; 2014, GreenKahuna, Steven Skoczen and the individual contributors.
# google_analytics: ['UA-1234567-8', 'skoczen.github.io/will']