version: '3.2'

services:
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    will:
        image:  harbor.columncloud.com/will/will-release-next
        ports:
            - 80:8080
        depends_on:
            - redis
