version: '3.2'

services:
    redis:
        image: redis:alpine
    will:
        image:  harbor.columncloud.com/will/will-release_next
        ports:
            - 80:8080
        depends_on:
            - redis
